AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWP Image Workshop - AI Image Generation and Editing

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

  StageName:
    Type: String
    Default: v1

Globals:
  Function:
    Timeout: 120
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - arm64
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

Resources:
  # Lambda Function
  ImageWorkshopFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub awp-image-workshop-${Environment}
      Handler: dist/index.handler
      CodeUri: .
      Description: AWP Image Workshop MCP Server
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource:
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/awp-image-workshop/*
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:awp-image-workshop/*
      Events:
        McpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2022'
        Sourcemap: false
        EntryPoints:
          - src/index.ts
        External:
          - '@aws-sdk/*'
        Loader:
          - .md=text

  # HTTP API Gateway
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Description: AWP Image Workshop API
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Signature
          - X-Timestamp
        AllowMethods:
          - GET
          - POST
          - OPTIONS

  # CloudWatch Log Group
  ImageWorkshopLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/awp-image-workshop-${Environment}
      RetentionInDays: 14

Outputs:
  ApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}

  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt ImageWorkshopFunction.Arn

  FunctionName:
    Description: Lambda function name
    Value: !Ref ImageWorkshopFunction
