AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Fullstack Template - SAM backend + React frontend

# ==============================================================================
# Global Configuration
# ==============================================================================
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64

# ==============================================================================
# Parameters - Customize these for your project
# ==============================================================================
Parameters:
  CustomDomainName:
    Type: String
    Description: Custom domain name for CloudFront (e.g. app.example.com). Requires CustomDomainCertificateArn.
    Default: ""
  CustomDomainCertificateArn:
    Type: String
    Description: ACM certificate ARN for custom domain (must be in us-east-1).
    Default: ""

# ==============================================================================
# Conditions
# ==============================================================================
Conditions:
  HasCustomDomain: !And 
    - !Not [!Equals [!Ref CustomDomainName, ""]]
    - !Not [!Equals [!Ref CustomDomainCertificateArn, ""]]

# ==============================================================================
# Resources
# ==============================================================================
Resources:

  # ============================================================================
  # S3 Bucket for WebUI Static Files
  # ============================================================================
  UiBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-ui-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  UiBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UiBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${UiBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # ============================================================================
  # CloudFront Distribution
  # ============================================================================
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: !If
          - HasCustomDomain
          - - !Ref CustomDomainName
          - !Ref AWS::NoValue
        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref CustomDomainCertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        Origins:
          # S3 Origin for static files
          - Id: S3Origin
            DomainName: !GetAtt UiBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ""
          # API Gateway Origin for /api/* routes
          - Id: ApiOrigin
            DomainName: !Sub "${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: /prod
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
        CacheBehaviors:
          # Route /api/* to API Gateway
          - PathPattern: /api/*
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD]
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac  # AllViewerExceptHostHeader
            ResponseHeadersPolicyId: !Ref CorsResponseHeadersPolicy
          # Also route /api (without trailing slash)
          - PathPattern: /api
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD]
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac  # AllViewerExceptHostHeader
            ResponseHeadersPolicyId: !Ref CorsResponseHeadersPolicy
        CustomErrorResponses:
          # SPA routing - redirect 404/403 to index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100

  CorsResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${AWS::StackName}-cors-policy"
        CorsConfig:
          AccessControlAllowCredentials: false
          AccessControlAllowHeaders:
            Items:
              - Content-Type
              - Authorization
              - X-Requested-With
          AccessControlAllowMethods:
            Items:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
          AccessControlAllowOrigins:
            Items:
              - "*"
          AccessControlMaxAgeSec: 86400
          OriginOverride: true

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # ============================================================================
  # Lambda Function
  # ============================================================================
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-handler"
      CodeUri: backend/dist/
      Handler: handler.handler
      Environment:
        Variables:
          NODE_OPTIONS: "--enable-source-maps"
          # Add your environment variables here
      # Add policies as needed:
      # Policies:
      #   - DynamoDBCrudPolicy:
      #       TableName: !Ref MyTable
      Events:
        ProxyRoute:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway
        RootRoute:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref ApiGateway

  # ============================================================================
  # API Gateway
  # ============================================================================
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      StageName: prod
      BinaryMediaTypes:
        - "application/octet-stream"
        - "multipart/form-data"
        - "*/*"

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
  
  UiBucketName:
    Description: S3 bucket for WebUI static files
    Value: !Ref UiBucket

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution

  CloudFrontUrl:
    Description: CloudFront Distribution URL
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
