AWSTemplateFormatVersion: '2010-09-09'
Description: AWP Shared Authentication Infrastructure - Cognito User Pool with Google and Microsoft IdP

Parameters:
  CognitoDomain:
    Type: String
    Description: Cognito hosted UI domain prefix (must be globally unique, e.g. 'awp-auth')
    Default: ""
  GoogleClientId:
    Type: String
    Description: Google OAuth 2.0 Client ID (for Sign in with Google)
    Default: ""
  GoogleClientSecret:
    Type: String
    NoEcho: true
    Description: Google OAuth 2.0 Client Secret (for Sign in with Google)
    Default: ""
  MicrosoftClientId:
    Type: String
    Description: Microsoft (Azure AD) Application (client) ID
    Default: ""
  MicrosoftClientSecret:
    Type: String
    NoEcho: true
    Description: Microsoft (Azure AD) Client Secret
    Default: ""

Conditions:
  HasCognitoDomain: !Not [!Equals [!Ref CognitoDomain, ""]]
  HasGoogleIdP: !And [!Not [!Equals [!Ref GoogleClientId, ""]], !Not [!Equals [!Ref GoogleClientSecret, ""]]]
  HasMicrosoftIdP: !And [!Not [!Equals [!Ref MicrosoftClientId, ""]], !Not [!Equals [!Ref MicrosoftClientSecret, ""]]]

Resources:
  # ============================================================================
  # Cognito User Pool
  # ============================================================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-users"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false

  # ============================================================================
  # Identity Providers
  # ============================================================================
  UserPoolGoogleIdP:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasGoogleIdP
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: "openid email profile"
      AttributeMapping:
        email: email
        name: name

  UserPoolMicrosoftIdP:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasMicrosoftIdP
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Microsoft
      ProviderType: OIDC
      ProviderDetails:
        client_id: !Ref MicrosoftClientId
        client_secret: !Ref MicrosoftClientSecret
        authorize_scopes: "openid email profile"
        # Microsoft common tenant for personal + work/school accounts
        oidc_issuer: "https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0"
        attributes_request_method: "GET"
      AttributeMapping:
        email: email
        name: name
        username: sub

  # ============================================================================
  # Cognito Domain (for Hosted UI)
  # ============================================================================
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Condition: HasCognitoDomain
    Properties:
      Domain: !Ref CognitoDomain
      UserPoolId: !Ref UserPool

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolArn"

  CognitoDomainPrefix:
    Condition: HasCognitoDomain
    Description: Cognito Hosted UI domain prefix
    Value: !Ref CognitoDomain
    Export:
      Name: !Sub "${AWS::StackName}-CognitoDomainPrefix"

  CognitoHostedUiUrl:
    Condition: HasCognitoDomain
    Description: Cognito Hosted UI base URL
    Value: !Sub "https://${CognitoDomain}.auth.${AWS::Region}.amazoncognito.com"
    Export:
      Name: !Sub "${AWS::StackName}-CognitoHostedUiUrl"

  HasGoogleIdP:
    Description: Whether Google IdP is configured
    Value: !If [HasGoogleIdP, "true", "false"]
    Export:
      Name: !Sub "${AWS::StackName}-HasGoogleIdP"

  HasMicrosoftIdP:
    Description: Whether Microsoft IdP is configured
    Value: !If [HasMicrosoftIdP, "true", "false"]
    Export:
      Name: !Sub "${AWS::StackName}-HasMicrosoftIdP"
