AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWP Agent Service - Lightweight storage provider with Cognito authentication

# ============================================================================
# Parameters
# ============================================================================
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

  BlobExpirationDays:
    Type: Number
    Default: 1
    Description: Days before output blobs expire

# ============================================================================
# Globals
# ============================================================================
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"
        ENVIRONMENT: !Ref Environment

# ============================================================================
# Resources
# ============================================================================
Resources:
  # --------------------------------------------------------------------------
  # Cognito User Pool
  # --------------------------------------------------------------------------
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "awp-agent-service-${Environment}"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      # For dev, auto-verify emails (skip SES)
      # For prod, remove this and configure SES
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true
      UserPoolTags:
        Environment: !Ref Environment

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "awp-agent-service-client-${Environment}"
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days

  # --------------------------------------------------------------------------
  # S3 Blob Storage
  # --------------------------------------------------------------------------
  BlobBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "awp-agent-blobs-${Environment}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - Id: AllowAgentAccess
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            ExposedHeaders:
              - ETag
              - Content-Type
              - Content-Length
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOutputBlobs
            Status: Enabled
            Prefix: output/
            ExpirationInDays: !Ref BlobExpirationDays
          - Id: ExpireTempBlobs
            Status: Enabled
            Prefix: temp/
            ExpirationInDays: 1
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # --------------------------------------------------------------------------
  # API Gateway
  # --------------------------------------------------------------------------
  AgentServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "awp-agent-service-api-${Environment}"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      BinaryMediaTypes:
        - "image/*"
        - "application/octet-stream"
        - "*/*"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization'"

  # --------------------------------------------------------------------------
  # Lambda Function
  # --------------------------------------------------------------------------
  AgentServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "awp-agent-service-${Environment}"
      CodeUri: dist/
      Handler: handler.handler
      Description: AWP Agent Service - Storage provider and authentication
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          USER_POOL_CLIENT_ID: !Ref UserPoolClient
          BLOB_BUCKET: !Ref BlobBucket
          AWS_REGION_NAME: !Ref AWS::Region
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BlobBucket
      Events:
        ProxyRoute:
          Type: Api
          Properties:
            RestApiId: !Ref AgentServiceApi
            Path: /{proxy+}
            Method: ANY
        RootRoute:
          Type: Api
          Properties:
            RestApiId: !Ref AgentServiceApi
            Path: /
            Method: ANY

# ============================================================================
# Outputs
# ============================================================================
Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${AgentServiceApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolClientId"

  BlobBucketName:
    Description: S3 Bucket for blob storage
    Value: !Ref BlobBucket
    Export:
      Name: !Sub "${AWS::StackName}-BlobBucket"

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolArn"
